### ISSUE TITLE
Undeclared dependency

### ISSUE THREAD

**Issue by MaithriRao** [sign-language-processing/segmentation#2]
Running `python -m sign_language_segmentation.src.train` results in the following traceback:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/path/to/segmentation/sign_language_segmentation/src/train.py", line 13, in <module>
    from .data import get_dataset, PoseSegmentsDataset
  File "/path/to/thesis/segmentation/sign_language_segmentation/src/data.py", line 8, in <module>
    from _shared.tfds_dataset import ProcessedPoseDatum, get_tfds_dataset
ModuleNotFoundError: No module named '_shared'
```
One way to make that module available is by installing `transcription`: `pip install git+https://github.com/sign-
language-processing/transcription`. But this is not described in the README. Maybe that module should just be part of this repository instead.

**Comment by AmitMY** [comment]
Thanks for reporting this - you are right, the `ProcessedPoseDatum, get_tfds_dataset` are missing from this repo. I will try to figure out the best way to add everything right now. In the meanwhile, your patch works.
